SELECT
	PERIODO, 
	AGENCIA, 
	CODCENT AS CC, 
	CONTRATO, 
	CLAVE AS CARTERA, 
	FOCO AS PRIORIDAD, 
	CAPITALSOLES AS CAPITAL, 
	PAGOEFECTTOTALSOLESAGENCIACONT AS RECUPERO, 
	SEGMENTO_RIESGO AS SEGMENTO, 
	AMBITO_RCD_FINAL AS PRODUCTO, 
	INTENSIDAD AS INTENSIDAD_TOTAL, 
	DIRECTO_CALL AS INTENSIDAD_DIRECTA, 
	COBERTURA,
	--CONTACTO_EFECTIVO AS CONTACTO_DIRECTO, 
	PDP, 
	--TASA_CIERRE, 
	PDP_CUMPLIDA
FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
WHERE 1 = 1 
AND PERIODO = '202503' 
AND FECHA = (SELECT MAX(FECHA)
			FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
			WHERE PERIODO = '202503')
--AND CODCENT = '24825925'

/*
SELECT *
FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
WHERE PERIODO ='202503'
*/

/*
SELECT MAX(FECHA) as FECHA_ACTUALIZACION
FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
WHERE PERIODO ='202503'
*/

/*
SELECT *
FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
WHERE 1=1 
AND PERIODO ='202502' 
AND FECHA = (SELECT MAX(FECHA)
			FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
			WHERE PERIODO ='202502')
*/


SELECT 
    F_SALIDAS AS PERIODO, 
    AGENCIA, 
    CODCENTRAL AS COD_CENTRAL, 
    CONT_SAE AS CONTRATO, 
    CASE 
        WHEN ENTIDAD = 'KST' THEN 'KSTBC' 
        ELSE ENTIDAD 
    END AS MARCA, 
    FOCO AS TRAMO, 
    FECHA_SALIDAS AS FECHA_PAGO, 
    EFECTIVO AS MONTO_PAGO
FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA
WHERE 1=1
    AND AGENCIA IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA')
    AND ENTIDAD IN ('BC', 'EXJ', 'KST')
    --AND FOCO IN ('C1', 'C2', 'C3')
    AND EFECTIVO > 0
    AND F_SALIDAS IN ('202412', '202501', '202502', '202503')
	--AND CONT_SAE = '00110267005001274257'
	AND CODCENTRAL = '29232326'
ORDER BY PERIODO, FECHA_PAGO, AGENCIA, MARCA, TRAMO, COD_CENTRAL ASC




SELECT 
    F_SALIDAS AS PERIODO, 
    AGENCIA, 
    CODCENTRAL AS COD_CENTRAL, 
    CONT_SAE AS CONTRATO, 
    CASE 
        WHEN ENTIDAD = 'KST' THEN 'KSTBC' 
        ELSE ENTIDAD 
    END AS MARCA, 
    FOCO AS TRAMO, 
    FECHA_SALIDAS AS FECHA_PAGO, 
    EFECTIVO AS MONTO_PAGO
FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA
WHERE 1=1
    AND AGENCIA IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA')
    AND ENTIDAD IN ('BC', 'EXJ', 'KST')
    --AND FOCO IN ('C1', 'C2', 'C3')
    AND EFECTIVO > 0
    AND F_SALIDAS IN ('202503')
ORDER BY PERIODO, FECHA_PAGO, AGENCIA, MARCA, TRAMO, COD_CENTRAL ASC




SELECT
	SUM(PAGOEFECTTOTALSOLESAGENCIACONT) AS RECUPERO
FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
WHERE 1 = 1 
AND PERIODO = '202503' 
AND FECHA = (SELECT MAX(FECHA)
			FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
			WHERE PERIODO = '202503')


SELECT
    agencia AS AGENCIA, 
    codigo AS COD_CENTRAL, 
    cont_18 AS CONTRATO, 
    clave AS MARCA, 
    FOCO AS TRAMO,
    nombre AS NOMBRE_CLIENTE, 
    moneda AS MONEDA, 
    CAPITAL, 
    Camp AS CAMP, 
    TIPO_FONDO, 
    TIPO_CARTERA, 
    PRODUCTO, 
    fechadatos as FECHA_DATOS
FROM FB.CENTROCOBRANZAS.DBO.PD_DISTRIBUCION_TARDIA_HOY
WHERE 1=1 
    AND agencia IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA', 'SIN AGENCIA')
    AND clave IN ('BC', 'EXJ', 'KSTBC', 'CDT')
    AND FOCO IN ('C1', 'C2', 'C3')
    AND fechadatos = (
        SELECT MAX(fechadatos) 
        FROM FB.CENTROCOBRANZAS.DBO.PD_DISTRIBUCION_TARDIA_HOY
        WHERE 1=1 
            AND agencia IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA', 'SIN AGENCIA')
            AND clave IN ('BC', 'EXJ', 'KSTBC', 'CDT')
            AND FOCO IN ('C1', 'C2', 'C3')
	)