SELECT 
    PERIODO, 
    AGENCIA, 
    CLAVE,
    SUM(CAPITALSOLES) AS CAPITAL, 
    SUM(PAGOEFECTTOTALSOLESAGENCIACONT) AS RECUPERO,
    SUM(PAGOEFECTTOTALSOLESAGENCIACONT) / SUM(CAPITALSOLES) AS EFECTIVIDAD
FROM (
    SELECT
        PERIODO, 
        AGENCIA, 
        CODCENT, 
        CLAVE, 
        FOCO, 
        CAPITALSOLES, 
        PAGOEFECTTOTALSOLESAGENCIACONT, 
        SEGMENTO_RIESGO, 
        AMBITO_RCD_FINAL, 
        COBERTURA, 
        INTENSIDAD, 
        CONTACTO_EFECTIVO, 
        DIRECTO_CALL, 
        PDP_CUMPLIDA, 
        TASA_CIERRE
    FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
    WHERE PERIODO = '202501' 
    AND FECHA = (
        SELECT MAX(FECHA)
        FROM FB.CENTROCOBRANZAS.DBO.PD_EFECTIVIDAD_TARDIA_HISTORICO
        WHERE PERIODO = '202501'
    )
) AS Subquery
WHERE AGENCIA IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA')
GROUP BY PERIODO, AGENCIA, CLAVE
ORDER BY PERIODO, AGENCIA, CLAVE