--SELECT * FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA -- RECUPERO JUDICIAL
--SELECT * FROM FB.CENTROCOBRANZAS.DBO.PD_STOCK_TARDIA -- STOCK CARTERA TARDIA


WITH MaxDiaPago AS (
    SELECT F_SALIDAS, MAX(DIA_PAGO) AS MaxDIA_PAGO
    FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA
    WHERE F_SALIDAS IN ('202502')
    GROUP BY F_SALIDAS
)
SELECT t.*
FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA AS t
INNER JOIN MaxDiaPago AS m
ON t.F_SALIDAS = m.F_SALIDAS AND t.DIA_PAGO = m.MaxDIA_PAGO
WHERE AGENCIA IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA')







SELECT 
	F_SALIDAS AS PERIODO, 
	AGENCIA, 
	CODCENTRAL AS COD_CENTRAL, 
	CONT_SAE AS CONTRATO, 
	CASE 
		WHEN ENTIDAD = 'KST' THEN 'KSTBC' 
		ELSE ENTIDAD 
	END AS MARCA, 
	FOCO AS TRAMO, 
	FECHA_SALIDAS AS FECHA_PAGO, 
	LIQUIDO, 
	EFECTIVO
FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA
WHERE 1=1
	AND AGENCIA IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA')
	AND ENTIDAD IN ('BC', 'EXJ', 'KST')
	AND FOCO IN ('C1', 'C2', 'C3')
	AND EFECTIVO > 0
	AND F_SALIDAS IN ('202412', '202501', '202502')
	AND DIA_PAGO <=4
ORDER BY PERIODO, FECHA_PAGO, AGENCIA, MARCA, TRAMO, COD_CENTRAL ASC






SELECT
    SUM(LIQUIDO) AS SUMA_LIQUIDO, 
    SUM(TRANSACCION_REFINANCIADO) AS SUMA_TRANSACCION_REFINANCIADO, 
    SUM(EFECTIVO) AS SUMA_EFECTIVO 
FROM 
    FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA 
WHERE 
    AGENCIA IN ('ASESCOM RJ', 'CLASA MORA', 'MORNESE MORA') 
    AND F_SALIDAS = '202502' 
    AND DIA_PAGO <= 3 
GROUP BY 
    DIA_PAGO