--SELECT * FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA -- RECUPERO JUDICIAL
--SELECT * FROM FB.CENTROCOBRANZAS.DBO.PD_STOCK_TARDIA -- STOCK CARTERA TARDIA


WITH MaxDiaPago AS (
    SELECT F_SALIDAS, MAX(DIA_PAGO) AS MaxDIA_PAGO
    FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA
    WHERE F_SALIDAS IN ('202411', '202412', '202501')
    GROUP BY F_SALIDAS
)
SELECT t.*
FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA AS t
INNER JOIN MaxDiaPago AS m
ON t.F_SALIDAS = m.F_SALIDAS AND t.DIA_PAGO = m.MaxDIA_PAGO

	
SELECT * FROM FB.CENTROCOBRANZAS.DBO.PD_RECUPERO_TARDIA
WHERE F_SALIDAS = '202411' AND DIA_PAGO = 29